<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <RootNamespace>Acme</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Shop\Basket.vb" />
    <Compile Include="Included.vb" />
  </ItemGroup>
</Project>
